#!/usr/bin/env bash
# ============================================================================
# YouTube Downloader Installer Script
# ============================================================================
# This script automates the installation of the YouTube Downloader app.
# It creates a portable installation that works for any user with custom paths.
# Whoever reads this can easily verify the code is safe to run.
# ============================================================================

# SECTION 1: SAFETY & ERROR HANDLING
# ============================================================================
# 'set -euo pipefail' means:
#   -e: exit immediately if any command fails
#   -u: exit if any undefined variable is used
#   -o pipefail: exit if any command in a pipeline fails
set -euo pipefail

# This trap catches errors and prints which line and command failed for debugging
trap 'echo "\n[Installer] Error on line $LINENO while running: $BASH_COMMAND" >&2' ERR

# SECTION 2: LOCATE THE INSTALLER DIRECTORY
# ============================================================================
# Find the folder where this install.sh script is located (the package folder)
# This is where all the source files (youtube_downloader.zsh, etc.) are stored
INSTALLER_DIR="$(cd "$(dirname "$0")" && pwd)"

# SECTION 3: USER INPUT - ASK FOR INSTALLATION PATH
# ============================================================================
# Display a warning that the app must be installed in the user's home directory
echo "⚠️  INSTALL APP INTO FOLDER IN USER HOME DIRECTORY ⚠️"
echo "Example: /Users/$(whoami)/YouTube Downloader"

# Prompt the user to enter the exact folder path where they want to install
echo -n "Enter the full install folder path: "
read -r INSTALL_DIR

# SECTION 4: VALIDATE USER INPUT
# ============================================================================
# Check if the user entered an empty path
if [ -z "$INSTALL_DIR" ]; then
  echo "No install path provided. Aborting."
  exit 1
fi

# Check if the user chose a path outside their home directory
# "$HOME"* means "starts with the user's home directory"
if [[ "$INSTALL_DIR" != "$HOME"* ]]; then
  echo "WARNING: you chose a path outside your home directory."
  echo "The installer is designed for user-local installs and may fail without sudo."
  echo -n "Continue anyway? (y/N) "
  read -r CONTINUE
  # [[ ! "$CONTINUE" =~ ^[Yy]$ ]] means "if the user did NOT type Y or y"
  if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
    echo "Aborted by user."
    exit 1
  fi
fi

# SECTION 5: CREATE THE INSTALLATION DIRECTORY
# ============================================================================
# 'mkdir -p' creates the folder and all parent folders if they don't exist
# The -p flag means "create parent directories as needed" (don't fail if it exists)
mkdir -p "$INSTALL_DIR"

# SECTION 6: COPY CORE APP FILES
# ============================================================================
# Copy the main shell script that runs the downloader
cp -f "$INSTALLER_DIR/youtube_downloader.zsh" "$INSTALL_DIR/"

# Copy the configuration template (will be used later to generate the real config)
cp -f "$INSTALLER_DIR/config.sh.template" "$INSTALL_DIR/"

# SECTION 7: COPY RUSTYPIPE-BOTGUARD (DEPENDENCY FOR PO TOKEN SUPPORT)
# ============================================================================
# Check if the rustypipe-botguard binary (pre-compiled executable) exists locally
# This binary helps fetch PO tokens needed for HQ YouTube Music downloads
if [ -f "$INSTALLER_DIR/rustypipe-botguard" ]; then
  cp -f "$INSTALLER_DIR/rustypipe-botguard" "$INSTALL_DIR/"
fi

# Search for a rustypipe-botguard archive file (.tar.xz or .tar.gz)
# 'find' looks in the installer directory for these archive files
# 'head -n 1' takes only the first match (if multiple exist)
# '|| true' means "if find returns nothing, that's okay, don't fail"
BOTGUARD_ARCHIVE=$(find "$INSTALLER_DIR" -maxdepth 1 -type f \( -iname 'rustypipe-botguard*.tar.xz' -o -iname 'rustypipe-botguard*.tar.gz' \) | head -n 1 || true)

# If an archive was found, copy it to the install directory (it will be extracted later)
if [ -n "$BOTGUARD_ARCHIVE" ]; then
  cp -f "$BOTGUARD_ARCHIVE" "$INSTALL_DIR/"
fi

# SECTION 8: GENERATE PERSONALIZED CONFIG.SH FILE
# ============================================================================
# Define where the config.sh file will be created
CONFIG_FILE="$INSTALL_DIR/config.sh"

# Create config.sh by writing content between <<EOF and EOF
# This is called a "here document" and lets us write multi-line content
cat > "$CONFIG_FILE" <<EOF
#!/bin/zsh

# YouTube Downloader Configuration generated by install.sh
# These paths tell the script where to find files and where to save downloads
INSTALL_ROOT="$INSTALL_DIR"
BASE_DIR="\$INSTALL_ROOT/yt-dlp"
COOKIE_FILE="\$INSTALL_ROOT/cookies.txt"
LOG_FILE="\$INSTALL_ROOT/download_log_file.txt"
EOF

# Make the config.sh file executable (chmod +x = add execute permission)
chmod +x "$CONFIG_FILE"

# SECTION 8B: INSTALL PYTHON SSL CERTIFICATES
# ============================================================================
# Runs the macOS Python certificate installer to ensure SSL works correctly.
# This is required for pip and yt-dlp to make secure HTTPS connections.
CERT_SCRIPT="/Applications/Python 3.12/Install Certificates.command"

if [ -f "$CERT_SCRIPT" ]; then
  echo "Running Python certificate installer..."
  bash "$CERT_SCRIPT"
  echo "Certificate installation complete."
else
  echo "Warning: Python 3.12 certificate installer not found at expected path. Skipping."
  echo "If you encounter SSL errors, run it manually from /Applications/Python 3.12/"
fi

# Wait a moment to ensure certificates are fully installed before proceeding
sleep 5 

# SECTION 9: INSTALL PYTHON DEPENDENCIES
# ============================================================================
# Check if python3 or python is available on the system
# This finds which Python interpreter to use for pip commands
if command -v python3 >/dev/null 2>&1; then
  PYTHON=python3
elif command -v python >/dev/null 2>&1; then
  PYTHON=python
else
  echo "Python3 not found. Install Python 3 and rerun this installer."
  exit 1
fi

# Install yt-dlp-get-pot using pip (installs to user's local site-packages, no sudo needed)
# --user: install only for current user (in ~/.local/)
# -U: upgrade if already installed
echo "Installing yt-dlp-get-pot into the user Python environment..."
$PYTHON -m pip install --user -U yt-dlp-get-pot

# Upgrade pip itself to the latest version (optional, || true means "ignore errors")
# '|| true' prevents the script from failing if pip upgrade fails
if command -v pip3 >/dev/null 2>&1; then
  pip3 install --upgrade pip || true
fi

# SECTION 10: CREATE APPLICATION SUPPORT FOLDER
# ============================================================================
# macOS apps store data in ~/Library/Application Support/
# The downloader uses this to store the PID file (used to cancel downloads)
APP_SUPPORT_DIR="$HOME/Library/Application Support/YouTube Downloader"
mkdir -p "$APP_SUPPORT_DIR"

# SECTION 11: MAKE SCRIPTS EXECUTABLE
# ============================================================================
# chmod +x adds "execute" permission so the shell script can be run as a program
chmod +x "$INSTALL_DIR/youtube_downloader.zsh"

# SECTION 12: EXTRACT & CONFIGURE RUSTYPIPE-BOTGUARD
# ============================================================================
# Check if the binary already exists (from step 7)
if [ -f "$INSTALL_DIR/rustypipe-botguard" ]; then
  chmod +x "$INSTALL_DIR/rustypipe-botguard"
  echo "Copied rustypipe-botguard binary and made it executable."

# Otherwise, check if an archive was copied and extract it
elif [ -n "$BOTGUARD_ARCHIVE" ]; then
  echo "Extracting rustypipe-botguard archive..."
  # 'pushd' changes directory and saves the current location on a stack
  pushd "$INSTALL_DIR" >/dev/null
  
  # Extract the archive: tar -xvf means extract verbose (show files as they're extracted)
  tar -xvf "$(basename "$BOTGUARD_ARCHIVE")"
  
  # Wait 3 second to ensure extraction is fully complete before proceeding
  sleep 3
  
  # Check if the extraction was successful by verifying the binary exists
  if [ -f "$INSTALL_DIR/rustypipe-botguard" ]; then
    chmod +x "$INSTALL_DIR/rustypipe-botguard"
    echo "Extracted and made rustypipe-botguard executable."
  else
    echo "Warning: rustypipe-botguard binary not found after extraction."
  fi
  
  # 'popd' returns to the previous directory (undoes the pushd)
  popd >/dev/null
fi

# SECTION 13: GENERATE APPLESCRIPT WRAPPER FOR THIS INSTALL
# ============================================================================
# Create a fresh AppleScript source file that points to the chosen install path.
APPLESCRIPT_SOURCE="$INSTALL_DIR/youtube_downloader_app.applescript"
cat > "$APPLESCRIPT_SOURCE" <<EOF
on run
    set scriptPath to "$INSTALL_DIR/youtube_downloader.zsh"
    do shell script "export PATH=/opt/homebrew/bin:/usr/local/bin:\$PATH; nohup /usr/bin/env zsh \"" & scriptPath & "\" >/dev/null 2>&1 &"
end run
EOF

# SECTION 13B: CREATE README.TXT FILE
# ============================================================================
README_FILE="$INSTALL_DIR/README.txt"
cat > "$README_FILE" <<'EOF'

######################################################################################
####################/////////////////////////////////////////////#####################
####################\\WELCOME TO PREMIUM YT-DLP DOWNLOADER TOOL\\#####################
####################/////////////////////////////////////////////#####################
######################################################################################


>>>>>>>>>>> The following instructions are meant for you to troubleshoot <<<<<<<<<
>>>>>>>>>>> and test when anything does not work as it should. You might <<<<<<<<<
>>>>>>>>>>>  need to run "sudo " command before some of the fixes below. <<<<<<<<<
>>>>>>>>>>>   If you installed everything, head down to next section!    <<<<<<<<<

// 1. First off, for this tool to perfectly work, you need to install the extension I
// provided in the installation. If you missed it here you go:


	https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc?hl=en


// 2. If something is still not working for 141 downloads, either you don't have proper 
// cookies set up or the PO Token fetching might not be properly installed. Proceed
// with the following instructions...

// 3. Run the following command in terminal to make sure you have python 3.12.1 or newer
// installed:


	pip3 install --upgrade pip


// 4.If not installed, go to official website and install, run the command ABOVE again
// and then execute the following 2 command in terminal:


	bash "/Applications/Python 3.12/Install Certificates.command"


// Then this one:


	python3 -m pip install -U yt-dlp-get-pot


// 5. If your root folder contains no "rustypipe-botguard" file or in case you do not
// own an Apple Silicon Mac (aarch64/ARM64), then go to this website, download 
// binaries and move the file to your downloader directory:


	https://codeberg.org/ThetaDev/rustypipe-botguard/releases


// NOTE THAT THE FILE I INCLUDED IN THE INSTALLATION IS STRICTLY FOR APPLE SILICON 
// (aarch64/ARM64) MACS. YOU NEED TO DOWNLOAD THE ONE THAT SUITS YOUR SYSTEM!

// Now run the following command in the terminal by replacing $DIR$ with the directory
// you installed the app into and then proceed with the next step:


	cd $DIR$


// Then run the following command to unpack it (once unpacked you can delete the
// compressed file) and replace $FILE$ with the exact file name including
// the extension:


	tar -xvf $FILE$


// If tracks are being downloaded but only in AIFF, check if your log file reads:
// "[!] No valid cookies found. Skipping HQ (141) attempt."
// If error present, this is 100% the issue!


---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------


HOW TO USE THIS TOOL:

// NOTE THAT IF YOU DO NOT OWN AN APPLE SILICON MAC, SOME OF THE STEPS BELOW MIGHT NOT
// BE APPLICABLE TO YOU. IN THIS CASE, GO READ THE INSTRUCTIONS ABOVE (SECTION 5) TO 
// FIX YOUR INSTALLATION AND THEN PROCEED...

1. First go to your preferred browser (Chrome confirmed working) and log in to your
	YouTube music premium account (otherwise you will only get compressed m4a files
	

2. Click the cookies extension and click on "Export all cookies". You should now have
	a file called cookies.txt which you now need to move into the root folder.
	(cookie files need to be re-downloaded every 24 hours usually)


// The following steps only apply to playlists. If you want to download only one track,
// skip to step 12. :


3. Open F12Develeoper_Tool_Command.txt inside the root folder and copy it entirely.


4. Go to your YouTube music playlist (preferably music.youtube.com URL) and scroll
	to the very bottom of the playlist and make sure the last track is loaded


5. Press F12 or right click anywhere on the website, click "Inspect" and go to the 	"Console" tab


6. Now paste what you copied from the developer tool txt file. You might need to 
	enter "allow pasting" before being able to


7. Copy all links that get returned as they are. Make sure you don't copy any other 
	characters!


8. Create a new txt file with TextEdit and click "Format" in the top bar of your screen


9. Click "Make plain text"


10. Paste your links and MAKE SURE TO HIT ENTER AFTER THE LAST ONE so the script ends
	one line below your last URL


11. Save the file anywhere on your pc.


12. Chose whether you want to create a new folder or chose an existing one
	(if no "yt-dlp" folder exists within the root, choosing an existing one is
	not possible yet)


13. (Only for create new folder) Name your folder


14. (Only for single track) Enter URL (preferably music.youtube.com URL)


15. Head to the root folder and find your high quality tracks in the [HQ 256k] folder
	and your lower quality AIFF files in the [Fallback AIFF] folder


16. If you want to cancel a download you accidentally started, double click/run the 
	app again and your download will cancel

17. Enjoy :)


-Nutcracker

Thanks for downloading. -Nutcracker :)

BTC donations welcome to support my work:
15hMZCUhPZs9tMAoVUR3YY4ZLxAKebo3wU (btc network)

EOF

echo "Created README.txt"

# SECTION 14: COMPILE APPLESCRIPT INTO A NATIVE MACOS APP
# ============================================================================
# Define the name of the compiled app
APP_NAME="YouTube Downloader.app"

# Check if 'osacompile' command is available (it compiles AppleScript on macOS)
if command -v osacompile >/dev/null 2>&1; then
  
  # Check if the AppleScript source file exists
  if [ -f "$APPLESCRIPT_SOURCE" ]; then
    
    # Compile the AppleScript into a native .app bundle
    # -o: specifies the output file path
    osacompile -o "$INSTALL_DIR/$APP_NAME" "$APPLESCRIPT_SOURCE"
    
    echo "Compiled AppleScript into $INSTALL_DIR/$APP_NAME"
    
    # Remove the source .applescript file since it's no longer needed
    # (the .app is self-contained and portable)
    rm -f "$APPLESCRIPT_SOURCE"
  else
    echo "No AppleScript source file found in install directory."
  fi
else
  echo "osascript compiler not found. AppleScript app not built."
fi

# SECTION 13A: CREATE COPY LINKS INSTRUCTION FILE
# ============================================================================
# Create a .txt file in the install root containing the exact helper script.
# This file can be opened and copied from Finder.
COPY_LINKS_FILE="$INSTALL_DIR/F12Developer_Tool_Command.txt"
cat > "$COPY_LINKS_FILE" <<'EOF'
const allLinks = Array.from(document.querySelectorAll('a'));
const watchLinks = allLinks
  .map(a => a.href)
  .filter(href => href.includes('watch?v='));

const uniqueLinks = [...new Set(watchLinks)];
console.log(uniqueLinks.join('\n'));

//#########*** PRESS ENTER AFTER LAST URL IN URL.txt ***#########
EOF

echo "Created helper link file: F12Developer_Tool_Command.txt"

# Try to add a yellow Finder tag if possible
if command -v osascript >/dev/null 2>&1; then
  osascript -e "tell application \"Finder\" to set label index of (POSIX file \"$COPY_LINKS_FILE\" as alias) to 5" 2>/dev/null || true
fi

# SECTION 14: DISPLAY INSTALLATION SUMMARY
# ============================================================================
# Show the user what was installed and where
cat <<EOF
Installation complete.

Installed files into: $INSTALL_DIR
- youtube_downloader.zsh
- config.sh
- $APP_NAME (if osacompile succeeded)

Please place your cookies.txt in:
$INSTALL_DIR/cookies.txt

Note: The downloaded files will be stored under:
$INSTALL_DIR/yt-dlp
EOF

# SECTION 15: OFFER TO OPEN COOKIE EXTRACTOR SETUP
# ============================================================================
# Define the URL for the Chrome extension that exports cookies
COOKIE_GUIDE_URL="https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc?hl=en"

# Check if the 'open' command is available (macOS command to open URLs)
if command -v open >/dev/null 2>&1; then
  echo -n "Would you like to open the cookie extractor setup page now? (y/N) "
  read -r OPEN_COOKIES
  
  # If the user typed 'y' or 'Y', open the URL
  if [[ "$OPEN_COOKIES" =~ ^[Yy]$ ]]; then
    open "$COOKIE_GUIDE_URL"
  fi
fi

# SECTION 16: CLEAN UP TEMPORARY FILES
# ============================================================================
# Remove the template file (no longer needed, real config.sh was generated)
rm -f "$INSTALL_DIR/config.sh.template"

# Remove any rustypipe-botguard archive files (.tar.xz or .tar.gz)
# These are no longer needed since the binary is extracted
rm -f "$INSTALL_DIR"/rustypipe-botguard*.tar.xz
rm -f "$INSTALL_DIR"/rustypipe-botguard*.tar.gz

# SECTION 17: FINAL MESSAGE
# ============================================================================
echo ""
echo "############# ⚠️ ⚠️ ⚠️  CHECK OUT README.TXT AFTER INSTALLATION ⚠️ ⚠️ ⚠️  #############"
echo ""
echo "Thanks for downloading. -Nutcracker :)"
echo ""
echo "BTC donations welcome to support my work:"
echo "15hMZCUhPZs9tMAoVUR3YY4ZLxAKebo3wU (btc network)"
echo ""

# SECTION 18: EXIT THE INSTALLER
# ============================================================================
# 'exit 0' means "exit successfully" (0 = no errors)
exit 0
