#!/bin/zsh

# Source the configuration file (generated by installer)
CONFIG_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$CONFIG_DIR/config.sh" ]; then
    source "$CONFIG_DIR/config.sh"
else
    echo "Error: config.sh not found in $CONFIG_DIR"
    exit 1
fi

#1 ==============================================================================
#1 1. PATHS & INITIALIZATION
#1 ==============================================================================

# Add brew path so the script can find yt-dlp and ffmpeg
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

# Initialize the log file by clearing it and adding a timestamp
echo "--- New Download Session: $(date) ---
" > "$LOG_FILE"

# Variable to hold a brief summary for the end of the session
ERROR_SUMMARY=""
DOWNLOAD_SUCCESS=0
URL_DETECTED=0

# PID file for cancel-on-relaunch support
PID_DIR="$HOME/Library/Application Support/YouTube Downloader"
PID_FILE="$PID_DIR/download.pid"

ensure_pid_dir() {
    mkdir -p "$PID_DIR"
}

cleanup_pid_file() {
    rm -f "$PID_FILE"
}

cleanup_popup() {
    if [ -n "$POPUP_PID" ]; then
        kill "$POPUP_PID" 2>/dev/null || true
    fi
}

write_pid_file() {
    ensure_pid_dir
    # Write the current shell PID so subsequent launcher invocations can cancel this process
    printf '%s' "$$" > "$PID_FILE"
}

is_pid_running() {
    local pid="$1"
    [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null
}

# This function checks for an existing PID file and attempts to cancel the running process if found. It also handles the case where the PID file exists but the process is not running.
cancel_existing_download() {
    if [ -f "$PID_FILE" ]; then
        local existing_pid
        existing_pid=$(cat "$PID_FILE" 2>/dev/null)
        if is_pid_running "$existing_pid"; then
            osascript -e 'display dialog "A download is already running...
            Clicking OK will cancel it." buttons {"OK"} default button "OK"' 2>/dev/null
            kill -TERM "$existing_pid" 2>/dev/null
            kill -TERM "-$existing_pid" 2>/dev/null
            sleep 1
            if is_pid_running "$existing_pid"; then
                kill -KILL "$existing_pid" 2>/dev/null
                kill -KILL "-$existing_pid" 2>/dev/null
            fi
            echo "[Cancel] Existing download canceled by relaunch." >> "$LOG_FILE"
            cleanup_pid_file
            osascript -e 'display dialog "Download canceled." buttons {"OK"} default button "OK"' 2>/dev/null
            exit 0
        else
            echo "[Info] Found stale PID file for non-running process; removing." >> "$LOG_FILE"
            cleanup_pid_file
        fi
    fi
}

trap 'cleanup_pid_file; cleanup_popup' EXIT
trap 'echo "[Cancel] Download process terminated by external cancel request at $(date)." >> "$LOG_FILE"; cleanup_pid_file; cleanup_popup; exit 1' INT TERM

#1 ==============================================================================
#1 2. URL SANITIZATION
#1 ==============================================================================
#1 This function fixes country-coded domains and enforces the music.youtube.com standard
sanitize_url() {
    local INPUT_LINK="$1"
    
    # Strip any &list=... tag to prevent playlist processing/redirects
    INPUT_LINK=$(echo "$INPUT_LINK" | sed 's/&list=[^&]*//g')
    
    echo "[Log] Processing URL: $INPUT_LINK
" >> "$LOG_FILE"

    # ========== STEP 1: DETECT & ADD MUSIC PREFIX ==========
    if [[ "$INPUT_LINK" != *"music."* ]]; then
        echo "[Log] Generic YouTube link detected - no 'music' prefix found.
" >> "$LOG_FILE"
        
        # Check for www.youtube pattern first
        if [[ "$INPUT_LINK" == *"www.youtube"* ]]; then
            echo "[Log] Found www.youtube pattern. Replacing 'www' with 'music'.
" >> "$LOG_FILE"
            INPUT_LINK=$(echo "$INPUT_LINK" | sed 's/www\.youtube\./music.youtube./g')
        fi
        
        # If still no music prefix, handle youtube.X pattern
        if [[ "$INPUT_LINK" != *"music."* ]]; then
            echo "[Log] Still no music prefix. Replacing 'youtube.' with 'music.youtube.'.
" >> "$LOG_FILE"
            INPUT_LINK=$(echo "$INPUT_LINK" | sed 's/youtube\./music.youtube./g')
        fi
    else
        echo "[Log] Music YouTube link already detected. Proceeding to domain normalization.
" >> "$LOG_FILE"
    fi

    # ========== STEP 2: NORMALIZE COUNTRY CODE EXTENSIONS ==========
    
    # 2A: Handle multi-part country codes (.co.xx) - DO THIS FIRST
    if [[ "$INPUT_LINK" == *"youtube.co."* ]]; then
        echo "[Log] Multi-part country code (.co.xx) detected in domain.
" >> "$LOG_FILE"
        INPUT_LINK=$(echo "$INPUT_LINK" | sed -E 's/music\.youtube\.co\.[a-z]{2}/music.youtube.com/g')
        echo "[Log] Converted .co.xx to .com.
" >> "$LOG_FILE"
    fi
    
    # 2B: Handle 2-letter country domain codes (.xx)
    if [[ "$INPUT_LINK" =~ music\.youtube\.[a-z]{2}([/?]|$) ]]; then
        echo "[Log] 2-letter country domain code (.xx) detected in domain.
" >> "$LOG_FILE"
        INPUT_LINK=$(echo "$INPUT_LINK" | sed -E 's/music\.youtube\.[a-z]{2}([/?]|$)/music.youtube.com\1/g')
        echo "[Log] Converted .xx to .com.
" >> "$LOG_FILE"
    fi
    
    # 2C: Handle 3-letter country domain codes (.xxx)
    if [[ "$INPUT_LINK" =~ music\.youtube\.[a-z]{3} ]] && [[ "$INPUT_LINK" != *".com"* ]]; then
        echo "[Log] 3-letter country domain code (.xxx) detected in domain.
" >> "$LOG_FILE"
        INPUT_LINK=$(echo "$INPUT_LINK" | sed -E 's/music\.youtube\.[a-z]{3}([/?]|$)/music.youtube.com\1/g')
        echo "[Log] Converted .xxx to .com.
" >> "$LOG_FILE"
    fi
    
    echo "[Log] Finalized Sanitized URL: $INPUT_LINK
" >> "$LOG_FILE"
    echo "$INPUT_LINK"
}

#1 ==============================================================================
#1 3. DOWNLOAD ENGINE
#1 ==============================================================================
#1 Handles both HQ (141) and AIFF (Fallback) download logic
download_track() {
    local URL="$1"
    local HQ_DIR="$2"
    local FALLBACK_DIR="$3"
    
    # Extract track title for logging
    # MODIFIED: Added --no-playlist to ensure consistency
    TITLE=$(yt-dlp --get-title --no-playlist "$URL" 2>/dev/null || echo "Unknown_Track")
    echo "[Task] Downloading: $TITLE
" >> "$LOG_FILE"

# Sanitize title for filesystem (replace problematic characters with underscores)
TITLE=$(echo "$TITLE" | tr '|/\\:*?"<>' '_')

    # A. Attempt HQ (141) download using authenticated cookies
    if [ -f "$COOKIE_FILE" ] && [ -s "$COOKIE_FILE" ]; then
        echo "[Task] Cookies detected. Attempting HQ (141) download.
" >> "$LOG_FILE"
        # MODIFIED: Added --no-playlist to prevent playlist container interference
        yt-dlp --cookies "$COOKIE_FILE" --no-playlist \
          --extractor-args "youtube:player_client=mweb;formats=missing_pot" \
          -f "141" \
          --add-metadata \
          --embed-thumbnail \
          -o "$HQ_DIR/%(title)s.%(ext)s" \
          "$URL" >> "$LOG_FILE" 2>&1
        
        # Check if the HQ download was successful
        if [ $? -eq 0 ]; then
            echo "[Success] Downloaded HQ (141) for $TITLE.
" >> "$LOG_FILE"
            ERROR_SUMMARY+="\n[OK] $TITLE -> Saved as HQ (141)"
            return 0
        fi
        echo "[!] HQ (141) download failed for $TITLE.
" >> "$LOG_FILE"
    else
        echo "[!] No valid cookies found. Skipping HQ (141) attempt.
" >> "$LOG_FILE"
    fi

    # B. AIFF Fallback Pipeline (if 141 is unavailable or cookies missing)
    echo "[Task] Initiating AIFF fallback pipeline for $TITLE.
" >> "$LOG_FILE"
    # MODIFIED: Added --no-playlist to ensure single-track focus
    yt-dlp --ffmpeg-location "/opt/homebrew/bin/ffmpeg" --no-playlist \
      -f "bestaudio[ext=webm]" \
      --write-thumbnail \
      --convert-thumbnails jpg \
      -x \
      --audio-format wav \
      -o "$FALLBACK_DIR/%(title)s.%(ext)s" \
      "$URL" >> "$LOG_FILE" 2>&1
    if [ $? -ne 0 ]; then
      echo "[ERROR] Fallback download failed for $TITLE.
" >> "$LOG_FILE"
      ERROR_SUMMARY+="\n[ERROR] No URLs have been detected. Could not proceed to download!"
      return 1
    fi
    
    # Convert resulting wav file to AIFF with metadata/cover art
    WAV_FILE=$(find "$FALLBACK_DIR" -maxdepth 1 -name "*.wav" | head -n 1)
    JPG_FILE=$(find "$FALLBACK_DIR" -maxdepth 1 -name "*.jpg" | head -n 1)
    /opt/homebrew/bin/ffmpeg -i "$WAV_FILE" -i "$JPG_FILE" \
      -map 0:a -map 1:v \
      -c:a pcm_s16be \
      -c:v mjpeg \
      -disposition:v attached_pic \
      -metadata title="$TITLE" \
      -id3v2_version 3 \
      -write_id3v2 1 \
      "$FALLBACK_DIR/$TITLE.aiff" >> "$LOG_FILE" 2>&1
    if [ $? -ne 0 ]; then
      echo "[ERROR] AIFF conversion failed for $TITLE.
" >> "$LOG_FILE"
      rm -f "$WAV_FILE" "$JPG_FILE"
      ERROR_SUMMARY+="\n[ERROR] No URLs have been detected. Could not proceed to download!"
      return 1
    fi
    
    # Clean up temporary files
    rm -f "$WAV_FILE" "$JPG_FILE"
    echo "[Success] Downloaded and converted $TITLE to AIFF.
" >> "$LOG_FILE"
    ERROR_SUMMARY+="\n[!] $TITLE -> Fallback to AIFF"
    return 0
}

#1 ==============================================================================
#1 4. USER INTERFACE & FOLDER SETUP
#1 ==============================================================================
#1 Prompt user for mode and target folder

NEW_TARGET_CREATED=0

cleanup_on_cancel() {
    if [ "$NEW_TARGET_CREATED" = "1" ] && [ -n "$TARGET" ] && [ -d "$TARGET" ]; then
        rm -rf "$TARGET"
        echo "[Cancel] Removed newly created target directory: $TARGET
" >> "$LOG_FILE"
    fi
}

# Helper to run osascript and exit cleanly if the user cancels a dialog
ask() {
    local out
    out=$(osascript "$@" 2>/dev/null) || { echo "[Cancel] User canceled dialog." >> "$LOG_FILE"; cleanup_on_cancel; exit 0; }
    printf '%s' "$out"
}

cancel_existing_download

PLAYLIST_CHOICE=$(ask -e 'display dialog "What are you downloading?" buttons {"Single Track", "Playlist"} default button "Playlist"')
if [ -z "$PLAYLIST_CHOICE" ]; then
    echo "[Cancel] Empty response for download choice; aborting." >> "$LOG_FILE"
    exit 0
fi
CHOICE=$(ask -e 'display dialog "Folder Setup?" buttons {"Create New", "Choose Existing"} default button "Create New"')
if [ -z "$CHOICE" ]; then
    echo "[Cancel] Empty response for folder setup choice; aborting." >> "$LOG_FILE"
    exit 0
fi

# Create folder structure based on user choice
if [ "$CHOICE" = "button returned:Create New" ]; then
    echo "New Folder created!
" >> "$LOG_FILE"
    NAME=$(ask -e 'display dialog "Folder Name:" default answer ""' -e 'text returned of result')
    if [ -z "$NAME" ]; then
        echo "[Cancel] Empty folder name; aborting." >> "$LOG_FILE"
        exit 0
    fi
    TARGET="$BASE_DIR/$NAME"
    mkdir -p "$TARGET"
    NEW_TARGET_CREATED=1
    HQ_DIR="$TARGET/[HQ-256k]"
    FALLBACK_DIR="$TARGET/[Fallback-AIFF]"
    mkdir -p "$HQ_DIR" "$FALLBACK_DIR"
    echo "[Setup] Created new target and subfolders: $HQ_DIR, $FALLBACK_DIR
" >> "$LOG_FILE"
else
    echo "Existing folder chosen!
" >> "$LOG_FILE"
    TARGET=$(ask -e "tell application \"Finder\" to POSIX path of (choose folder with prompt \"Select folder:\" default location (POSIX file \"$BASE_DIR\"))")
    if [ -z "$TARGET" ]; then
        echo "[Cancel] No folder selected; aborting." >> "$LOG_FILE"
        exit 0
    fi
    HQ_DIR="$TARGET/[HQ-256k]"
    FALLBACK_DIR="$TARGET/[Fallback-AIFF]"
    if [ ! -d "$HQ_DIR" ]; then
        mkdir -p "$HQ_DIR"
        echo "[Setup] Created missing folder: $HQ_DIR
" >> "$LOG_FILE"
    fi
    if [ ! -d "$FALLBACK_DIR" ]; then
        mkdir -p "$FALLBACK_DIR"
        echo "[Setup] Created missing folder: $FALLBACK_DIR
" >> "$LOG_FILE"
    fi
fi

# Sanitize target path string and navigate to directory
TARGET=$(echo "$TARGET" | tr -d '\n\r')
cd "$TARGET"

#1 ==============================================================================
#1 5. EXECUTION LOGIC
#1 ==============================================================================
#1 Handle single URL or iterate through a filtered text file for playlists
if [ "$PLAYLIST_CHOICE" = "button returned:Single Track" ]; then
    echo "Single Track chosen to download!
" >> "$LOG_FILE"
    RAW=$(ask -e 'tell application "System Events" to activate' -e 'display dialog "Enter URL:" default answer ""' -e 'text returned of result')
    if [ -z "$RAW" ]; then
        echo "[Cancel] No URL entered; aborting." >> "$LOG_FILE"
        exit 0
    fi
    write_pid_file
    # Show "Downloading" progress alert in background (start popup now that we have a URL)
    osascript -e 'display dialog "Track(s) downloading... Please wait." buttons {"OK"} default button "OK"' 2>/dev/null &
    POPUP_PID=$!
    if download_track "$(sanitize_url "$RAW")" "$HQ_DIR" "$FALLBACK_DIR"; then
        DOWNLOAD_SUCCESS=1
    fi
else
    echo "Playlist chosen to download!
" >> "$LOG_FILE"
    TXT_FILE=$(ask -e "tell application \"Finder\" to POSIX path of (choose file of type {\"txt\"} with prompt \"Select playlist_urls.txt:\")")
    if [ -z "$TXT_FILE" ]; then
        echo "[Cancel] No playlist file selected; aborting." >> "$LOG_FILE"
        exit 0
    fi
    
    write_pid_file
    # Show "Downloading" progress alert in background (start popup now that we have playlist file)
    osascript -e 'display dialog "Track(s) downloading... Please wait." buttons {"OK"} default button "OK"' 2>/dev/null &
    POPUP_PID=$!
    
    # This reads the file line-by-line
    while IFS= read -r VIDEO_URL; do
        
        # This is the filter:
        # It checks if the line is empty OR if the line DOES NOT contain "list=PL"
        if [[ -z "$VIDEO_URL" || "$VIDEO_URL" != *"list=PL"* ]]; then
            
            # If the condition is met, it logs that it is skipping and jumps to the next line
            echo "[Skip] Non-playlist URL ignored: $VIDEO_URL
" >> "$LOG_FILE"
            continue
        fi
        
        # If the code reaches here, the URL is valid, so it proceeds to download
        # MODIFIED: Passing via sanitize_url ensures &list= is stripped before processing
        URL_DETECTED=1
        if download_track "$(sanitize_url "$VIDEO_URL")" "$HQ_DIR" "$FALLBACK_DIR"; then
            DOWNLOAD_SUCCESS=1
        fi
        
        #To fly under the radar of youtube's bot detection, we add a random sleep time between downloads when processing playlists. 
        #This is skipped for single track mode to speed up the process since there's less risk of triggering anti-bot measures.
        SLEEP_TIME=$(( RANDOM % 8 + 9 ))
        echo "[Log] Waiting ${SLEEP_TIME} seconds before next track...
" >> "$LOG_FILE"
        sleep "$SLEEP_TIME"

    done < "$TXT_FILE"
    
    if [ "$URL_DETECTED" -eq 0 ]; then
        echo "[ERROR] No URLs have been detected. Could not proceed to download!
" >> "$LOG_FILE"
        ERROR_SUMMARY+="\n[ERROR] No URLs have been detected. Could not proceed to download!"
    fi
fi

#1 ==============================================================================
#1 6. SUMMARY & CLEANUP
#1 ==============================================================================
#1 Remove any empty download folders before finishing
if [ -d "$HQ_DIR" ] && [ -z "$(find "$HQ_DIR" -mindepth 1 -maxdepth 1 | head -n 1)" ]; then
    rm -rf "$HQ_DIR"
    echo "[Cleanup] Removed empty folder: $HQ_DIR
" >> "$LOG_FILE"
fi
if [ -d "$FALLBACK_DIR" ] && [ -z "$(find "$FALLBACK_DIR" -mindepth 1 -maxdepth 1 | head -n 1)" ]; then
    rm -rf "$FALLBACK_DIR"
    echo "[Cleanup] Removed empty folder: $FALLBACK_DIR
" >> "$LOG_FILE"
fi

#1 Write session summary and notify user
echo -e "\n\n--- SESSION SUMMARY ---$ERROR_SUMMARY" >> "$LOG_FILE"
kill $POPUP_PID 2>/dev/null
if [ "$DOWNLOAD_SUCCESS" -eq 1 ]; then
    osascript -e 'display dialog "Download complete, look into log file for more info." buttons {"OK"}'
else
    osascript -e 'display dialog "DOWNLOAD FAILED! PLEASE HEAD TO LOG FILE." buttons {"OK"}'
fi